"""
Action Registry - Command Handler Factory and Dispatcher.
Maps command types to their handler implementations.
Implements the Factory Pattern for centralized, decoupled command handling.
"""

from typing import Dict, Callable, List
from core.commands import Command, CommandHandler
from core.events import GameEvent
from core.models import AgentState


class ActionRegistry:
    """
    Factory and dispatcher for command handlers.
    Centralizes the mapping of Command Type -> Handler Implementation.
    
    This allows new commands to be added without modifying the GameEngine.
    """
    
    def __init__(self):
        self._handlers: Dict[str, CommandHandler] = {}
    
    def register(self, command_type: str, handler: CommandHandler) -> None:
        """
        Register a command handler.
        
        Args:
            command_type: The command type string (e.g., "SET_PRICE")
            handler: The CommandHandler implementation
        """
        self._handlers[command_type] = handler
    
    def execute(self, state: AgentState, command: Command) -> List[GameEvent]:
        """
        Execute a command by dispatching to the appropriate handler.
        
        Args:
            state: Current agent state (read-only)
            command: The command to execute
            
        Returns:
            List of events generated by the handler
            
        Raises:
            KeyError: If command type is not registered
        """
        if command.command_type not in self._handlers:
            raise KeyError(f"No handler registered for command type: {command.command_type}")
        
        handler = self._handlers[command.command_type]
        return handler.handle(state, command)
    
    def is_registered(self, command_type: str) -> bool:
        """Check if a command type is registered."""
        return command_type in self._handlers
    
    def get_registered_commands(self) -> List[str]:
        """Return list of all registered command types."""
        return list(self._handlers.keys())


__all__ = ["ActionRegistry"]
